version: "3"

services:

  systemhelper:
    build:
      context: ./
      dockerfile: Dockerfile
    image: lianshufeng/systemhelper
    privileged: true
    environment:
      - ntpd_host=cn.pool.ntp.org
      - uptetime_timer=86400
      - freemem_timer=7200
    volumes:
      # docker api
      - "/var/run/docker.sock:/var/run/docker.sock"
      # free mem
      - "/proc/sys/vm/drop_caches:/drop_caches"
      # log
      - "/var/log/systemhelper/:/var/log/"
      # store
      - "./store/:/store/"
    container_name: sh
    # update time auth
    cap_add:
      - SYS_TIME
    restart: always